### ISSUE TITLE
 ros2 launch xarm_description _robot_joint_state.launch.py 

### ISSUE THREAD

**Issue by NikolaRaicevic2001** [ExistentialRobotics/xarm_ros2#3]
1) The error: ros2 launch xarm_description _robot_joint_state.launch.py 
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-09-24-17-01-28-300472-nikolaraicevic-Legion-Pro-7-16IRX8H-17860
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [py]:
 - TypeError: generate_launch_description() missing 1 required positional argument: 'context'
 - InvalidFrontendLaunchFileError: The launch file may have a syntax error, or its format is unknown

2) Expected Behaviour: Publish robot model along with the joint states

3) Actual Behaviour: Throwen an error regarding context

**Comment by lkm1321** [comment]
To fix: 
- Ensure `generate_launch_description` does not take any argument
- For nodes that require `.perform(context)`, wrap it in a small OpaqueFunction (see https://github.com/ExistentialRobotics/xarm_ros2/blob/multi-robot/xarm_gazebo/launch/_robot_beside_table_gazebo.launch.py#L252) for example.
